import A12Kernel.Proofs.Information
import A12Kernel.Proofs.FullDate
import A12Kernel.Proofs.DateRangeOverlap
import A12Kernel.Proofs.DateRangeOverlapOperators
import A12Kernel.Proofs.DateConstruction
import A12Kernel.Proofs.DateConstructionNumeric
import A12Kernel.Proofs.DateTime
import A12Kernel.Proofs.DateTimeDifference
import A12Kernel.Proofs.Correlation
import A12Kernel.Proofs.CrossLevelCorrelation
import A12Kernel.Proofs.CorrelationElaboration
import A12Kernel.Proofs.Iteration
import A12Kernel.Proofs.NumericComparison
import A12Kernel.Proofs.NumericScale
import A12Kernel.Proofs.NumericExpression
import A12Kernel.Proofs.NumericTolerance
import A12Kernel.Proofs.NumericRounding
import A12Kernel.Proofs.NumericArithmetic
import A12Kernel.Proofs.NumericFillability
import A12Kernel.Proofs.NumericComputation
import A12Kernel.Proofs.NumericStoredNumber
import A12Kernel.Proofs.NumericTarget
import A12Kernel.Proofs.NumericApplication
import A12Kernel.Proofs.NumericDependency
import A12Kernel.Proofs.NumericValidation
import A12Kernel.Proofs.Elaboration
import A12Kernel.Proofs.ValidationRule
import A12Kernel.Proofs.Observation
import A12Kernel.Proofs.PartialValidation
import A12Kernel.Proofs.ComputationCondition
import A12Kernel.Proofs.ComputationFillQuantifier
import A12Kernel.Proofs.ValidationFillQuantifier
import A12Kernel.Proofs.GroupPresence
import A12Kernel.Proofs.GeneratedComputationValidation
import A12Kernel.Proofs.Required
import A12Kernel.Proofs.StringLength
import A12Kernel.Proofs.StringIngestion
import A12Kernel.Proofs.StringCascade
import A12Kernel.Proofs.StringAlternatives
import A12Kernel.Proofs.StringComputation
import A12Kernel.Proofs.StringApplication
import A12Kernel.Proofs.Verdict
import A12Kernel.Proofs.ValueList
import A12Kernel.Proofs.FirstFilledValue
import A12Kernel.Proofs.StarCompleteness
import A12Kernel.Proofs.NumericAggregate
import A12Kernel.Proofs.RepetitionNotUnique
import A12Kernel.Proofs.Enumeration
import A12Kernel.Proofs.EnumerationComparability
import A12Kernel.Proofs.SemanticIndex
import A12Kernel.Proofs.CustomCondition

/-! Trusted theorem root for the currently supported semantic fragment. -/
