import A12Kernel
import A12Kernel.Trust.Environment

/-!
The elaborated-environment audit is authoritative: it checks every declaration in the
trusted project modules regardless of source modifiers, attributes, or command macros.
Conformance modules are deliberately outside this root because their executable locks
may use `native_decide`. The explicit theorem reports below remain the human-readable
proof-spine registry.
-/

open Lean Lean.Elab Command

private def isAuditedLogicalModule (moduleName : Name) : Bool :=
  let text := moduleName.toString
  text == "A12Kernel" ||
    text == "A12Kernel.Basic" ||
    text == "A12Kernel.Core" ||
    text == "A12Kernel.Cell" ||
    text == "A12Kernel.Document" ||
    text == "A12Kernel.Proofs" ||
    text.startsWith "A12Kernel.Semantics." ||
    text.startsWith "A12Kernel.Elaboration." ||
    text.startsWith "A12Kernel.Proofs."

run_cmd do
  let (moduleCount, declarationCount) ←
    A12Kernel.Trust.auditImportedModules isAuditedLogicalModule
  logInfo m!"environment trust audit passed: {declarationCount} declarations in {moduleCount} modules"

#print axioms A12Kernel.K.and_commutative
#print axioms A12Kernel.K.and_associative
#print axioms A12Kernel.K.and_idempotent
#print axioms A12Kernel.K.or_commutative
#print axioms A12Kernel.K.or_associative
#print axioms A12Kernel.K.or_idempotent
#print axioms A12Kernel.K.and_tru_left
#print axioms A12Kernel.K.and_tru_right
#print axioms A12Kernel.K.and_fls_left
#print axioms A12Kernel.K.and_fls_right
#print axioms A12Kernel.K.or_fls_left
#print axioms A12Kernel.K.or_fls_right
#print axioms A12Kernel.K.or_tru_left
#print axioms A12Kernel.K.or_tru_right
#print axioms A12Kernel.K.and_absorbs_or
#print axioms A12Kernel.K.or_absorbs_and
#print axioms A12Kernel.K.and_distributes_over_or
#print axioms A12Kernel.K.or_distributes_over_and
#print axioms A12Kernel.K.informationRefines_refl
#print axioms A12Kernel.K.definite_true_stable
#print axioms A12Kernel.K.definite_false_stable
#print axioms A12Kernel.K.and_information_monotone
#print axioms A12Kernel.K.or_information_monotone

#print axioms A12Kernel.selectRows_iff
#print axioms A12Kernel.sumSelected_filter_before_consumer
#print axioms A12Kernel.outer_number_reference_stable
#print axioms A12Kernel.inner_number_reference_local
#print axioms A12Kernel.correlatedHaving_truth_iff_holds
#print axioms A12Kernel.selectCorrelatedRows_iff
#print axioms A12Kernel.evalGuardedAnyFilledOn_filter_before_consumer
#print axioms A12Kernel.currentRepetition_selfExclusion_false
#print axioms A12Kernel.explicitSelfExclusion_drops_outer
#print axioms A12Kernel.sameFieldEquality_selfMatches

#print axioms A12Kernel.checkedSingleCorrelatedRule_wellFormed
#print axioms A12Kernel.checkedSingleCorrelatedRule_modelWellFormed
#print axioms A12Kernel.rawSingleGroupContext_validate_wellFormed
#print axioms A12Kernel.admitsSingleGroupNumber_has_unique_matching_declaration
#print axioms A12Kernel.checkSingleGroupContext_lookup_coherent
#print axioms A12Kernel.checkSingleGroupContext_lookup_error_is_malformed
#print axioms A12Kernel.checkSingleGroupContext_wrong_group_is_malformed
#print axioms A12Kernel.checkSingleGroupContext_wrong_scope_is_malformed
#print axioms A12Kernel.checkSingleGroupContext_admittedNumber_coherent
#print axioms A12Kernel.correlatedHaving_wellFormed_equalityScalesAgree
#print axioms A12Kernel.resolvedSingleCorrelatedRule_wellFormed_equalityScalesAgree

#print axioms A12Kernel.Verdict.conj_commutative
#print axioms A12Kernel.Verdict.conj_associative
#print axioms A12Kernel.Verdict.conj_idempotent
#print axioms A12Kernel.Verdict.disj_commutative
#print axioms A12Kernel.Verdict.disj_associative
#print axioms A12Kernel.Verdict.disj_idempotent
#print axioms A12Kernel.Verdict.conj_fired_value_left
#print axioms A12Kernel.Verdict.conj_fired_value_right
#print axioms A12Kernel.Verdict.conj_notFired_left
#print axioms A12Kernel.Verdict.conj_notFired_right
#print axioms A12Kernel.Verdict.disj_notFired_left
#print axioms A12Kernel.Verdict.disj_notFired_right
#print axioms A12Kernel.Verdict.disj_fired_value_left
#print axioms A12Kernel.Verdict.disj_fired_value_right
#print axioms A12Kernel.Verdict.conj_absorbs_disj
#print axioms A12Kernel.Verdict.disj_absorbs_conj
#print axioms A12Kernel.Verdict.conj_distributes_over_disj
#print axioms A12Kernel.Verdict.disj_distributes_over_conj

#print axioms A12Kernel.formalCheck_wellFormed
#print axioms A12Kernel.withFinding_preserves_wellFormed
#print axioms A12Kernel.formalCheck_empty_observes_empty
#print axioms A12Kernel.formalCheck_parsedEmptyString_observes_empty
#print axioms A12Kernel.computation_observes_clean_value
#print axioms A12Kernel.computation_observes_single_poison
#print axioms A12Kernel.required_empty_observes_unknown_in_validation
#print axioms A12Kernel.required_empty_observes_empty_in_computation
#print axioms A12Kernel.ordinary_finding_still_poisons_computation

#print axioms A12Kernel.partialSelected_agreesOn
#print axioms A12Kernel.partialRule_fired_implies_fullWithContent_fired_of_agreesOn

#print axioms A12Kernel.fieldFilled_observedEmpty_notTrue
#print axioms A12Kernel.fieldNotFilled_observedEmpty_holds
#print axioms A12Kernel.fieldFilled_observedValue_holds
#print axioms A12Kernel.fieldNotFilled_observedValue_notTrue
#print axioms A12Kernel.fieldFilled_observedPoison_preserves
#print axioms A12Kernel.fieldNotFilled_observedPoison_preserves
#print axioms A12Kernel.requiredOnlyFieldNotFilled_holds
#print axioms A12Kernel.ordinaryFindingFieldNotFilled_poisons
#print axioms A12Kernel.presencePredicates_agree_on_poison
#print axioms A12Kernel.computationAnd_leftNotTrue_shortCircuits
#print axioms A12Kernel.computationAnd_leftHolds_evaluatesRight
#print axioms A12Kernel.computationAnd_leftPoison_preserves
#print axioms A12Kernel.computationOr_leftHolds_shortCircuits
#print axioms A12Kernel.computationOr_leftNotTrue_evaluatesRight
#print axioms A12Kernel.computationOr_leftPoison_preserves
#print axioms A12Kernel.computationAnd_operandOrderObservable
#print axioms A12Kernel.computationOr_operandOrderObservable
#print axioms A12Kernel.alternativeSelection_empty_is_noMatch
#print axioms A12Kernel.alternativeSelection_holdingHead_selects
#print axioms A12Kernel.alternativeSelection_notTrueHead_continues
#print axioms A12Kernel.alternativeSelection_poisonedHead_aborts
#print axioms A12Kernel.alternativeSelection_noMatch_iff
#print axioms A12Kernel.alternativeSelection_holdingOrderObservable
#print axioms A12Kernel.alternativeSelection_holdingPoisonOrderObservable

#print axioms A12Kernel.desugarAbsoluteRequired_preserves
#print axioms A12Kernel.withRequiredFinding_preserves_computation
#print axioms A12Kernel.applyAbsoluteRequired_preserves_computation
#print axioms A12Kernel.requiredFinding_empty_phase_split

#print axioms A12Kernel.checkedFlatCondition_wellFormed
#print axioms A12Kernel.checkedFlatCondition_modelWellFormed
#print axioms A12Kernel.admitsField_has_unique_matching_declaration
#print axioms A12Kernel.admitsComparison_has_unique_matching_declaration
#print axioms A12Kernel.checkContext_lookup_coherent
#print axioms A12Kernel.checkContext_admittedField_coherent
#print axioms A12Kernel.checkContext_admittedComparison_coherent
#print axioms A12Kernel.checkContext_lookup_error_is_malformed
#print axioms A12Kernel.checkContext_lookup_error_observes_unknown

#print axioms A12Kernel.fixedNumericFiring_is_value
#print axioms A12Kernel.numericEval_fixedRight
#print axioms A12Kernel.numericEqual_eval_comm
#print axioms A12Kernel.numericNotEqual_eval_comm
#print axioms A12Kernel.growOnlyGreaterEqualFiring_is_value
#print axioms A12Kernel.growOnlyLessFiring_is_omission
#print axioms A12Kernel.emptyNumberLessFiring_is_omission
#print axioms A12Kernel.emptyNumberGreaterEqualFiring_polarity
#print axioms A12Kernel.growOnlyNotEqualWhenLeftNotBelow_is_value
#print axioms A12Kernel.growOnlyRightGreaterEqualFiring_is_omission
#print axioms A12Kernel.growOnlyRightLessFiring_is_value
#print axioms A12Kernel.shrinkOnlyRightLessFiring_is_omission
#print axioms A12Kernel.scaleInfo_maxExact_comm
#print axioms A12Kernel.scaleInfo_addExact_comm
#print axioms A12Kernel.numericScale_binary_comm
#print axioms A12Kernel.exactNumericScaleComparisonAllowed_comm
#print axioms A12Kernel.exactNumericScaleComparisonAllowed_same
#print axioms A12Kernel.exactNumericScaleComparisonAllowed_of_left_lt
#print axioms A12Kernel.exactNumericScaleComparisonAllowed_fields
#print axioms A12Kernel.exactNumericScaleComparisonAllowed_unknown_left
#print axioms A12Kernel.exactNumericScaleComparisonAllowed_unknown_right
#print axioms A12Kernel.authoredNumericSummary_group
#print axioms A12Kernel.authoredNumericGroup_not_simple_constant
#print axioms A12Kernel.authoredNumericLower_group
#print axioms A12Kernel.lowerMultiply_two_divisions
#print axioms A12Kernel.lowerMultiply_left_division
#print axioms A12Kernel.lowerMultiply_right_division
#print axioms A12Kernel.lowerMultiply_without_divisions
#print axioms A12Kernel.lowerMultiply_nested_numerator_once
#print axioms A12Kernel.authoredNumericEval_uses_lowered_tree
#print axioms A12Kernel.numericAuthoring_single_division
#print axioms A12Kernel.numericAuthoring_addition_separates_divisions
#print axioms A12Kernel.numericAuthoring_group_separates_inner_and_outer_divisions
#print axioms A12Kernel.numericAuthoring_group_preserves_inner_division_violation
#print axioms A12Kernel.numericAuthoring_rejects_direct_left_power
#print axioms A12Kernel.numericAuthoring_group_allows_left_power
#print axioms A12Kernel.numericAuthoring_right_power_requires_parser_shape_boundary
#print axioms A12Kernel.numericAuthoring_round_is_outside_fragment
#print axioms A12Kernel.checkedNumericComparison_modelWellFormed
#print axioms A12Kernel.checkedNumericComparison_wellFormed
#print axioms A12Kernel.numericArithmetic_formalInvalid_left_is_unknown
#print axioms A12Kernel.numericArithmetic_formalInvalid_right_is_unknown
#print axioms A12Kernel.numericArithmetic_domainFailure_left_is_notFired
#print axioms A12Kernel.numericArithmetic_domainFailure_right_is_notFired
#print axioms A12Kernel.numericArithmetic_values_delegate
#print axioms A12Kernel.checkedNumericComparison_evaluations_areSome
#print axioms A12Kernel.numericComparison_atom_literal_agrees_flat
#print axioms A12Kernel.checkedNumericComparison_emptyRow_notFired
#print axioms A12Kernel.numericTolerance_threshold_pos
#print axioms A12Kernel.normalizedNumericDifference_comm
#print axioms A12Kernel.numericTolerance_holds_comm
#print axioms A12Kernel.numericDifferenceFillCanClose_comm_of_ne
#print axioms A12Kernel.numericTolerance_unknown_left
#print axioms A12Kernel.numericTolerance_unknown_right
#print axioms A12Kernel.numericTolerance_exactBoundary_notFired
#print axioms A12Kernel.fixedNumericToleranceFiring_is_value
#print axioms A12Kernel.growOnlyToleranceBelowFiring_is_omission
#print axioms A12Kernel.growOnlyToleranceNotBelowFiring_is_value
#print axioms A12Kernel.numericTolerance_eval_comm

#print axioms A12Kernel.rescaleFloor_le
#print axioms A12Kernel.le_rescaleCeiling
#print axioms A12Kernel.roundFloor_le_preRound
#print axioms A12Kernel.preRound_le_roundCeiling
#print axioms A12Kernel.numericOperand_round_unknown
#print axioms A12Kernel.numericOperand_round_value_preserves_fillability

#print axioms A12Kernel.roundMathContext50_zero
#print axioms A12Kernel.numericArithmetic_add_comm
#print axioms A12Kernel.numericArithmetic_multiply_comm
#print axioms A12Kernel.numericArithmetic_subtract_as_add_neg
#print axioms A12Kernel.numericArithmetic_multiply_zero
#print axioms A12Kernel.divideNumeric_zero
#print axioms A12Kernel.divideNumeric_of_ne_zero
#print axioms A12Kernel.divideNumeric_notEvaluated_iff
#print axioms A12Kernel.divideNumeric_zero_dividend
#print axioms A12Kernel.roundSignificantHalfUp_unlimited
#print axioms A12Kernel.positivePower_zero
#print axioms A12Kernel.powerNumeric_of_rejected_exponent
#print axioms A12Kernel.powerNumeric_of_nonnegative_exponent
#print axioms A12Kernel.powerNumeric_zero_exponent
#print axioms A12Kernel.powerNumeric_zero_negative_exponent
#print axioms A12Kernel.powerNumeric_negative_exponent
#print axioms A12Kernel.numericSign_ofRat_negative
#print axioms A12Kernel.numericSign_ofRat_zero
#print axioms A12Kernel.numericSign_ofRat_positive
#print axioms A12Kernel.numericArithmetic_fixed_fillability
#print axioms A12Kernel.numericFillability_add_comm
#print axioms A12Kernel.numericFillability_subtract_eq_add_swapped
#print axioms A12Kernel.numericFillability_subtract_fixed_right
#print axioms A12Kernel.numericFillability_fixed_subtract
#print axioms A12Kernel.numericFillability_multiply_comm
#print axioms A12Kernel.numericFillability_multiply_fixed_positive
#print axioms A12Kernel.numericFillability_multiply_fixed_negative
#print axioms A12Kernel.numericFillability_multiply_fixed_zero
#print axioms A12Kernel.numericArithmeticOutcome_eval_notEvaluated_left
#print axioms A12Kernel.numericArithmeticOutcome_eval_notEvaluated_right
#print axioms A12Kernel.numericArithmeticOutcome_divide_notEvaluated_left
#print axioms A12Kernel.numericArithmeticOutcome_divide_notEvaluated_right
#print axioms A12Kernel.numericArithmeticOutcome_divide_values_notEvaluated_iff
#print axioms A12Kernel.numericArithmeticOutcome_divide_fixed
#print axioms A12Kernel.numericArithmeticOutcome_divide_fixed_positive
#print axioms A12Kernel.numericArithmeticOutcome_divide_fixed_negative
#print axioms A12Kernel.numericArithmeticOutcome_divide_fixed_zero_dividend

#print axioms A12Kernel.directEmptyStringComparison_notFired
#print axioms A12Kernel.emptyStringLengthLess_fires_omission
#print axioms A12Kernel.emptyStringLengthGreaterEqual_fires_value
#print axioms A12Kernel.emptyString_operatorDistinction

#print axioms A12Kernel.normalizeEvaluatedString_crlfPrefix
#print axioms A12Kernel.normalizeEvaluatedString_notIdempotent
#print axioms A12Kernel.formalCheckString_cachesNormalized
#print axioms A12Kernel.checkedString_phasesReadNormalized
#print axioms A12Kernel.directStringOperand_readsNormalized
#print axioms A12Kernel.stringLengthOperand_readsNormalized
#print axioms A12Kernel.stringComputationField_readsNormalized

#print axioms A12Kernel.emptyStringField_evaluates_noValue
#print axioms A12Kernel.emptyStringField_concat_literal_stores_literal
#print axioms A12Kernel.poisonedStringField_evaluates_poison
#print axioms A12Kernel.poisonedLeftStringField_shortCircuits_concat
#print axioms A12Kernel.emptyLeftStringField_reads_poisonedRight
#print axioms A12Kernel.noValue_concat_text
#print axioms A12Kernel.text_concat_noValue
#print axioms A12Kernel.stringTerm_concat_associative
#print axioms A12Kernel.twoNoValues_concat_to_emptyText
#print axioms A12Kernel.finalEmptyString_is_noValue
#print axioms A12Kernel.concat_noValue_right_preserves_store
#print axioms A12Kernel.concat_noValue_left_preserves_store
#print axioms A12Kernel.concat_noValue_right_preserves_delta
#print axioms A12Kernel.concat_noValue_left_preserves_delta
#print axioms A12Kernel.concat_noValue_is_not_term_identity
#print axioms A12Kernel.noValue_delta_iff_prior_filled
#print axioms A12Kernel.poison_and_noValue_same_immediate_delta
#print axioms A12Kernel.poison_is_not_noValue
#print axioms A12Kernel.unchangedString_has_no_delta
#print axioms A12Kernel.changedString_has_value_delta
#print axioms A12Kernel.belowMinimumStringTarget_is_errored
#print axioms A12Kernel.aboveMaximumStringTarget_is_errored
#print axioms A12Kernel.minimumStringTarget_at_or_above_is_accepted
#print axioms A12Kernel.maximumStringTarget_at_or_below_is_accepted
#print axioms A12Kernel.minimumStringTarget_boundary_is_accepted
#print axioms A12Kernel.maximumStringTarget_boundary_is_accepted
#print axioms A12Kernel.lineBreakStringTarget_is_unsupported
#print axioms A12Kernel.noValue_bypassesStringTargetLength
#print axioms A12Kernel.poison_bypassesStringTargetLength
#print axioms A12Kernel.acceptedStringTarget_preserves_unconstrained_delta
#print axioms A12Kernel.unconstrainedStringTarget_preserves_store_delta
#print axioms A12Kernel.rejectedStringTarget_preserves_attempt
#print axioms A12Kernel.erroredStringTarget_reports_unconditionally
#print axioms A12Kernel.erroredStringTarget_has_no_appliedValue
#print axioms A12Kernel.acceptedStringTarget_applies_value
#print axioms A12Kernel.same_appliedValue_does_not_imply_same_delta

#print axioms A12Kernel.stringTargetApplies_iff_applyTo
#print axioms A12Kernel.stringTargetApplies_deterministic
#print axioms A12Kernel.acceptedStringTarget_applies_exactly
#print axioms A12Kernel.noAppliedStringValue_clears_exactly
#print axioms A12Kernel.noAppliedStringValue_preserves_presence
#print axioms A12Kernel.exactStringApplication_storedValue
#print axioms A12Kernel.equal_noValue_delta_does_not_imply_equal_exact_application
#print axioms A12Kernel.equal_exact_application_does_not_imply_equal_delta

#print axioms A12Kernel.dependencyOutcome_produces_wellFormedCell
#print axioms A12Kernel.dependencyCell_shadows_target
#print axioms A12Kernel.dependencyCell_preserves_other_read
#print axioms A12Kernel.dependencyOutcome_preserves_other_read
#print axioms A12Kernel.noValueDependency_reads_noValue
#print axioms A12Kernel.acceptedDependency_reads_value
#print axioms A12Kernel.erroredDependency_reads_declaredConstraintPoison
#print axioms A12Kernel.inheritedDependency_reads_samePoison
#print axioms A12Kernel.requiredDependencyPoison_is_rejected
#print axioms A12Kernel.erroredDependency_does_not_expose_attempt
#print axioms A12Kernel.stringStep_outcome_independent_of_prior
#print axioms A12Kernel.notTrueStringPrecondition_evaluates_noValue
#print axioms A12Kernel.holdingStringPrecondition_preserves_outcome
#print axioms A12Kernel.poisonedStringPrecondition_preserves_cause
#print axioms A12Kernel.holdingStringPrecondition_consumedInvalidField_poisons
#print axioms A12Kernel.same_delta_does_not_imply_same_dependency
#print axioms A12Kernel.same_appliedValue_does_not_imply_same_dependency
#print axioms A12Kernel.same_exact_application_does_not_imply_same_dependency_read
